redis:
  image: redis:3.0
  volumes:
    - "./redis:/data"

postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=changeme
    - POSTGRES_USER=sentry
  volumes:
    - "./postgres:/var/lib/postgresql/data"

sentry:
  build: sentry
  environment:
    - SENTRY_SECRET_KEY=changemetoo
  links:
    - redis:redis
    - postgres:postgres
  ports:
    - 9000:9000

sentry-celery-beat:
  build: sentry
  command: celery beat
  environment:
    - SENTRY_SECRET_KEY=changemetoo
  links:
    - redis:redis
    - postgres:postgres

sentry-celery-worker:
  build: sentry
  command: celery worker
  environment:
    - SENTRY_SECRET_KEY=changemetoo
  links:
    - redis:redis
    - postgres:postgres
